version: "3.4"

services:
  microrabbitmq.banking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Database=bankingDB;User=sa;Password=Pass@word
    ports:
      - "3000:80"

    depends_on:
      - rabbitmq
      - sql.data
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
